const experiences=[
{id:1,name:"Sabores del Caribe en Palenque",region:"Caribe",language:"Español",duration:4,type:"Gastronomía",location:"San Basilio de Palenque, Bolívar",price:145000,capacity:12,available:8,image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80",summary:"Cocina tradicional, memoria y música.",description:"Conoce recetas tradicionales y participa en una experiencia guiada por la comunidad."},
{id:2,name:"Ruta artesanal Zenú",region:"Caribe",language:"Español",duration:3,type:"Artesanía",location:"Tuchín, Córdoba",price:98000,capacity:10,available:4,image:"https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1200&q=80",summary:"Aprende el proceso artesanal de la caña flecha.",description:"Una experiencia práctica para conocer el tejido en caña flecha y su significado cultural."},
{id:3,name:"Senderos y aves del Pacífico",region:"Pacífica",language:"Inglés",duration:7,type:"Naturaleza",location:"Bahía Solano, Chocó",price:210000,capacity:8,available:0,image:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",summary:"Observación de aves y biodiversidad.",description:"Explora ecosistemas del Pacífico colombiano con guías locales."},
{id:4,name:"Memorias cafeteras",region:"Andina",language:"Español",duration:5,type:"Cultura",location:"Salento, Quindío",price:165000,capacity:14,available:6,image:"https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80",summary:"Del cultivo a la taza.",description:"Recorre una finca familiar y conoce el proceso del café."}
];let selected=experiences[0];
const money=v=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(v);
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.getElementById(id).classList.add("active");scrollTo(0,0)}
function render(items){cards.innerHTML=items.map(e=>`<article class="card"><img src="${e.image}"><div class="card-body"><small>${e.type}</small><h3>${e.name}</h3><p>${e.summary}</p><div class="meta"><span class="pill">${e.region}</span><span class="pill">${e.duration} h</span><span class="pill">${e.language}</span></div><div class="card-foot"><span class="price">${money(e.price)}</span><button class="primary" onclick="showDetail(${e.id})">Ver detalle</button></div></div></article>`).join("");count.textContent=`${items.length} resultados`;empty.classList.toggle("hidden",items.length>0)}
function applyFilters(){let r=region.value,l=language.value,d=duration.value,t=type.value;render(experiences.filter(e=>(!r||e.region===r)&&(!l||e.language===l)&&(!t||e.type===t)&&(!d||(d==="corta"&&e.duration<=3)||(d==="media"&&e.duration>=4&&e.duration<=6)||(d==="larga"&&e.duration>6))))}
function resetFilters(){[region,language,duration,type].forEach(x=>x.value="");render(experiences)}
function showDetail(id){selected=experiences.find(e=>e.id===id);detailContent.innerHTML=`<div class="detail-grid"><img src="${selected.image}"><section class="panel"><small>${selected.type} · ${selected.region}</small><h1>${selected.name}</h1><p>${selected.description}</p><div class="detail-list"><div class="detail-item">Ubicación<br><b>${selected.location}</b></div><div class="detail-item">Duración<br><b>${selected.duration} horas</b></div><div class="detail-item">Precio<br><b>${money(selected.price)}</b></div><div class="detail-item">Capacidad<br><b>${selected.capacity} personas</b></div><div class="detail-item">Idioma<br><b>${selected.language}</b></div><div class="detail-item">Disponibilidad<br><b>${selected.available>0?selected.available+" cupos":"Sin cupos"}</b></div></div><button class="primary wide" onclick="showReserve()">Solicitar reserva</button></section></div>`;show("detail")}
function showReserve(){reserveTitle.textContent=selected.name;summary.innerHTML=`<img src="${selected.image}"><h3>${selected.name}</h3><div class="row"><span>Ubicación</span><b>${selected.location}</b></div><div class="row"><span>Precio</span><b>${money(selected.price)}</b></div><div class="row"><span>Cupos</span><b>${selected.available}</b></div>`;message.className="notice hidden";show("reserve")}
function submitReservation(e){e.preventDefault();let p=Number(participants.value);if(selected.available===0||p>selected.available){message.textContent="No hay disponibilidad suficiente. Selecciona otra fecha o reduce los participantes.";message.className="notice error";return}let r={id:"RV-"+Date.now().toString().slice(-6),experience:selected.name,date:date.value,participants:p,status:"Pendiente"};let list=JSON.parse(localStorage.getItem("rvReservations")||"[]");list.push(r);localStorage.setItem("rvReservations",JSON.stringify(list));confirmationData.innerHTML=`<div class="row"><span>Solicitud</span><b>${r.id}</b></div><div class="row"><span>Experiencia</span><b>${r.experience}</b></div><div class="row"><span>Fecha</span><b>${r.date}</b></div><div class="row"><span>Participantes</span><b>${r.participants}</b></div><div class="row"><span>Estado</span><b>${r.status}</b></div>`;show("confirmation")}
function showReservations(){let list=JSON.parse(localStorage.getItem("rvReservations")||"[]");reservationList.innerHTML=list.length?list.map(r=>`<article class="reservation-item"><div><small>${r.id}</small><h3>${r.experience}</h3><p>${r.date} · ${r.participants} participantes</p></div><span class="status">${r.status}</span></article>`).join(""):`<div class="empty"><h3>Aún no tienes solicitudes</h3></div>`;show("reservations")}
render(experiences);